port: "8000"
excluded_paths:
  - "/health"
  - "/login"
  - "/register"
  - "/profiles/create"
  - "/images"

# Note: We need to use the format <service>:<port>
# no leading protocol : http:// or grpc://
# REST urls must have an ending slash
services:
  - name: "blog"
    rest_url: "http://blog:8080/"

  - name: "stakeholders"
    rest_url: "http://stakeholders:8082/"
    grpc_url: "stakeholders:50051"

  - name: "auth"
    rest_url: "http://auth:8081/"

  - name: "tours"
    rest_url: "http://tours:8083/"
    grpc_url: "tours:9093"

  - name: "follower"
    rest_url: "http://follower:8084/"

  - name: "purchases"
    grpc_url: "purchases:9095"