services:
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - service
    networks:
      - backend

  service:
    build:
      context: .
      dockerfile: ./Test/Dockerfile
    networks:
      - backend

networks:
  backend:
    driver: bridge