// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: tours/tours.proto

package tourspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourGrpcService_GetAllTours_FullMethodName = "/tours.TourGrpcService/GetAllTours"
	TourGrpcService_CreateTour_FullMethodName  = "/tours.TourGrpcService/CreateTour"
)

// TourGrpcServiceClient is the client API for TourGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourGrpcServiceClient interface {
	GetAllTours(ctx context.Context, in *GetAllToursRequest, opts ...grpc.CallOption) (*TourListResponse, error)
	CreateTour(ctx context.Context, in *CreateTourGrpcRequest, opts ...grpc.CallOption) (*TourGrpcResponse, error)
}

type tourGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourGrpcServiceClient(cc grpc.ClientConnInterface) TourGrpcServiceClient {
	return &tourGrpcServiceClient{cc}
}

func (c *tourGrpcServiceClient) GetAllTours(ctx context.Context, in *GetAllToursRequest, opts ...grpc.CallOption) (*TourListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourListResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_GetAllTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourGrpcServiceClient) CreateTour(ctx context.Context, in *CreateTourGrpcRequest, opts ...grpc.CallOption) (*TourGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourGrpcResponse)
	err := c.cc.Invoke(ctx, TourGrpcService_CreateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourGrpcServiceServer is the server API for TourGrpcService service.
// All implementations must embed UnimplementedTourGrpcServiceServer
// for forward compatibility.
type TourGrpcServiceServer interface {
	GetAllTours(context.Context, *GetAllToursRequest) (*TourListResponse, error)
	CreateTour(context.Context, *CreateTourGrpcRequest) (*TourGrpcResponse, error)
	mustEmbedUnimplementedTourGrpcServiceServer()
}

// UnimplementedTourGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourGrpcServiceServer struct{}

func (UnimplementedTourGrpcServiceServer) GetAllTours(context.Context, *GetAllToursRequest) (*TourListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTours not implemented")
}
func (UnimplementedTourGrpcServiceServer) CreateTour(context.Context, *CreateTourGrpcRequest) (*TourGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourGrpcServiceServer) mustEmbedUnimplementedTourGrpcServiceServer() {}
func (UnimplementedTourGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeTourGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourGrpcServiceServer will
// result in compilation errors.
type UnsafeTourGrpcServiceServer interface {
	mustEmbedUnimplementedTourGrpcServiceServer()
}

func RegisterTourGrpcServiceServer(s grpc.ServiceRegistrar, srv TourGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedTourGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourGrpcService_ServiceDesc, srv)
}

func _TourGrpcService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_GetAllTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).GetAllTours(ctx, req.(*GetAllToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourGrpcService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourGrpcServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourGrpcService_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourGrpcServiceServer).CreateTour(ctx, req.(*CreateTourGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourGrpcService_ServiceDesc is the grpc.ServiceDesc for TourGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.TourGrpcService",
	HandlerType: (*TourGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTours",
			Handler:    _TourGrpcService_GetAllTours_Handler,
		},
		{
			MethodName: "CreateTour",
			Handler:    _TourGrpcService_CreateTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}
