// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tours/tours.proto

package tourspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMyToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyToursRequest) Reset() {
	*x = GetMyToursRequest{}
	mi := &file_tours_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyToursRequest) ProtoMessage() {}

func (x *GetMyToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyToursRequest.ProtoReflect.Descriptor instead.
func (*GetMyToursRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

type CreateTourGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourGrpcRequest) Reset() {
	*x = CreateTourGrpcRequest{}
	mi := &file_tours_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourGrpcRequest) ProtoMessage() {}

func (x *CreateTourGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourGrpcRequest.ProtoReflect.Descriptor instead.
func (*CreateTourGrpcRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTourGrpcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourGrpcRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourGrpcRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourGrpcRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TourListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourGrpcResponse    `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListResponse) Reset() {
	*x = TourListResponse{}
	mi := &file_tours_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListResponse) ProtoMessage() {}

func (x *TourListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListResponse.ProtoReflect.Descriptor instead.
func (*TourListResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *TourListResponse) GetTours() []*TourGrpcResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type TourGrpcResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId       int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AuthorUsername string                 `protobuf:"bytes,3,opt,name=authorUsername,proto3" json:"authorUsername,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty     string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags           []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Price          float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TourGrpcResponse) Reset() {
	*x = TourGrpcResponse{}
	mi := &file_tours_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourGrpcResponse) ProtoMessage() {}

func (x *TourGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourGrpcResponse.ProtoReflect.Descriptor instead.
func (*TourGrpcResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *TourGrpcResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourGrpcResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TourGrpcResponse) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *TourGrpcResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourGrpcResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourGrpcResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourGrpcResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourGrpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourGrpcResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_tours_tours_proto protoreflect.FileDescriptor

const file_tours_tours_proto_rawDesc = "" +
	"\n" +
	"\x11tours/tours.proto\x12\x05tours\x1a\x1cgoogle/api/annotations.proto\"\x13\n" +
	"\x11GetMyToursRequest\"\x81\x01\n" +
	"\x15CreateTourGrpcRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"A\n" +
	"\x10TourListResponse\x12-\n" +
	"\x05tours\x18\x01 \x03(\v2\x17.tours.TourGrpcResponseR\x05tours\"\xfe\x01\n" +
	"\x10TourGrpcResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\x12&\n" +
	"\x0eauthorUsername\x18\x03 \x01(\tR\x0eauthorUsername\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price2\xbd\x01\n" +
	"\x0fTourGrpcService\x12R\n" +
	"\n" +
	"GetMyTours\x12\x18.tours.GetMyToursRequest\x1a\x17.tours.TourListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/tours/my\x12V\n" +
	"\n" +
	"CreateTour\x12\x1c.tours.CreateTourGrpcRequest\x1a\x17.tours.TourGrpcResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/toursB\x1dZ\x1bgateway/proto/tours;tourspbb\x06proto3"

var (
	file_tours_tours_proto_rawDescOnce sync.Once
	file_tours_tours_proto_rawDescData []byte
)

func file_tours_tours_proto_rawDescGZIP() []byte {
	file_tours_tours_proto_rawDescOnce.Do(func() {
		file_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)))
	})
	return file_tours_tours_proto_rawDescData
}

var file_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tours_tours_proto_goTypes = []any{
	(*GetMyToursRequest)(nil),     // 0: tours.GetMyToursRequest
	(*CreateTourGrpcRequest)(nil), // 1: tours.CreateTourGrpcRequest
	(*TourListResponse)(nil),      // 2: tours.TourListResponse
	(*TourGrpcResponse)(nil),      // 3: tours.TourGrpcResponse
}
var file_tours_tours_proto_depIdxs = []int32{
	3, // 0: tours.TourListResponse.tours:type_name -> tours.TourGrpcResponse
	0, // 1: tours.TourGrpcService.GetMyTours:input_type -> tours.GetMyToursRequest
	1, // 2: tours.TourGrpcService.CreateTour:input_type -> tours.CreateTourGrpcRequest
	2, // 3: tours.TourGrpcService.GetMyTours:output_type -> tours.TourListResponse
	3, // 4: tours.TourGrpcService.CreateTour:output_type -> tours.TourGrpcResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tours_tours_proto_init() }
func file_tours_tours_proto_init() {
	if File_tours_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tours_tours_proto_goTypes,
		DependencyIndexes: file_tours_tours_proto_depIdxs,
		MessageInfos:      file_tours_tours_proto_msgTypes,
	}.Build()
	File_tours_tours_proto = out.File
	file_tours_tours_proto_goTypes = nil
	file_tours_tours_proto_depIdxs = nil
}
