services:
  purchase-db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: purchase
      MYSQL_USER: purchase
      MYSQL_PASSWORD: purchase
    ports:
      - "3306:3306"

  purchases:
    build:
      context: ..
      dockerfile: Purchases/Dockerfile
    ports:
      - "50051:50051"
    environment:
      TOURS_SERVICE_URL: http://localhost:8000/tours
      STAKEHOLDERS_SERVICE_URL: http://localhost:8000/stakeholders
      JWT_SECRET: super-secret-change-me
    depends_on:
      - purchase-db