// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/purchase.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemRequest) Reset() {
	*x = OrderItemRequest{}
	mi := &file_proto_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemRequest) ProtoMessage() {}

func (x *OrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemRequest.ProtoReflect.Descriptor instead.
func (*OrderItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItemRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *OrderItemRequest) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *OrderItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponse) Reset() {
	*x = OrderItemResponse{}
	mi := &file_proto_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponse) ProtoMessage() {}

func (x *OrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponse.ProtoReflect.Descriptor instead.
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *OrderItemResponse) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *OrderItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_proto_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *AddToCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *AddToCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_proto_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFromCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Items         []*OrderItemResponse   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_proto_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *CartResponse) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *CartResponse) GetItems() []*OrderItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_proto_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *CheckoutRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,3,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	IssuedAt      string                 `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_purchase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *TokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenResponse) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TokenResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TokenResponse) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenResponse       `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_purchase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{7}
}

func (x *CheckoutResponse) GetTokens() []*TokenResponse {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type HasPurchasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedRequest) Reset() {
	*x = HasPurchasedRequest{}
	mi := &file_proto_purchase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedRequest) ProtoMessage() {}

func (x *HasPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedRequest.ProtoReflect.Descriptor instead.
func (*HasPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{8}
}

func (x *HasPurchasedRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *HasPurchasedRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type HasPurchasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchased     bool                   `protobuf:"varint,1,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedResponse) Reset() {
	*x = HasPurchasedResponse{}
	mi := &file_proto_purchase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedResponse) ProtoMessage() {}

func (x *HasPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedResponse.ProtoReflect.Descriptor instead.
func (*HasPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{9}
}

func (x *HasPurchasedResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

var File_proto_purchase_proto protoreflect.FileDescriptor

const file_proto_purchase_proto_rawDesc = "" +
	"\n" +
	"\x14proto/purchase.proto\x12\bpurchase\"^\n" +
	"\x10OrderItemRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"_\n" +
	"\x11OrderItemResponse\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"J\n" +
	"\x10AddToCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"O\n" +
	"\x15RemoveFromCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"\x81\x01\n" +
	"\fCartResponse\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.purchase.OrderItemResponseR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\"0\n" +
	"\x0fCheckoutRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\"t\n" +
	"\rTokenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x03 \x01(\tR\x06tourId\x12\x1b\n" +
	"\tissued_at\x18\x04 \x01(\tR\bissuedAt\"C\n" +
	"\x10CheckoutResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.purchase.TokenResponseR\x06tokens\"M\n" +
	"\x13HasPurchasedRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"4\n" +
	"\x14HasPurchasedResponse\x12\x1c\n" +
	"\tpurchased\x18\x01 \x01(\bR\tpurchased2\xaf\x02\n" +
	"\x0fPurchaseService\x12?\n" +
	"\tAddToCart\x12\x1a.purchase.AddToCartRequest\x1a\x16.purchase.CartResponse\x12I\n" +
	"\x0eRemoveFromCart\x12\x1f.purchase.RemoveFromCartRequest\x1a\x16.purchase.CartResponse\x12A\n" +
	"\bCheckout\x12\x19.purchase.CheckoutRequest\x1a\x1a.purchase.CheckoutResponse\x12M\n" +
	"\fHasPurchased\x12\x1d.purchase.HasPurchasedRequest\x1a\x1e.purchase.HasPurchasedResponseB\x15Z\x13purchase-service/pbb\x06proto3"

var (
	file_proto_purchase_proto_rawDescOnce sync.Once
	file_proto_purchase_proto_rawDescData []byte
)

func file_proto_purchase_proto_rawDescGZIP() []byte {
	file_proto_purchase_proto_rawDescOnce.Do(func() {
		file_proto_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)))
	})
	return file_proto_purchase_proto_rawDescData
}

var file_proto_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_purchase_proto_goTypes = []any{
	(*OrderItemRequest)(nil),      // 0: purchase.OrderItemRequest
	(*OrderItemResponse)(nil),     // 1: purchase.OrderItemResponse
	(*AddToCartRequest)(nil),      // 2: purchase.AddToCartRequest
	(*RemoveFromCartRequest)(nil), // 3: purchase.RemoveFromCartRequest
	(*CartResponse)(nil),          // 4: purchase.CartResponse
	(*CheckoutRequest)(nil),       // 5: purchase.CheckoutRequest
	(*TokenResponse)(nil),         // 6: purchase.TokenResponse
	(*CheckoutResponse)(nil),      // 7: purchase.CheckoutResponse
	(*HasPurchasedRequest)(nil),   // 8: purchase.HasPurchasedRequest
	(*HasPurchasedResponse)(nil),  // 9: purchase.HasPurchasedResponse
}
var file_proto_purchase_proto_depIdxs = []int32{
	1, // 0: purchase.CartResponse.items:type_name -> purchase.OrderItemResponse
	6, // 1: purchase.CheckoutResponse.tokens:type_name -> purchase.TokenResponse
	2, // 2: purchase.PurchaseService.AddToCart:input_type -> purchase.AddToCartRequest
	3, // 3: purchase.PurchaseService.RemoveFromCart:input_type -> purchase.RemoveFromCartRequest
	5, // 4: purchase.PurchaseService.Checkout:input_type -> purchase.CheckoutRequest
	8, // 5: purchase.PurchaseService.HasPurchased:input_type -> purchase.HasPurchasedRequest
	4, // 6: purchase.PurchaseService.AddToCart:output_type -> purchase.CartResponse
	4, // 7: purchase.PurchaseService.RemoveFromCart:output_type -> purchase.CartResponse
	7, // 8: purchase.PurchaseService.Checkout:output_type -> purchase.CheckoutResponse
	9, // 9: purchase.PurchaseService.HasPurchased:output_type -> purchase.HasPurchasedResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_purchase_proto_init() }
func file_proto_purchase_proto_init() {
	if File_proto_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_proto_goTypes,
		DependencyIndexes: file_proto_purchase_proto_depIdxs,
		MessageInfos:      file_proto_purchase_proto_msgTypes,
	}.Build()
	File_proto_purchase_proto = out.File
	file_proto_purchase_proto_goTypes = nil
	file_proto_purchase_proto_depIdxs = nil
}
