// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: purchase.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PurchaseService_AddToCart_FullMethodName       = "/purchase.PurchaseService/AddToCart"
	PurchaseService_RemoveFromCart_FullMethodName  = "/purchase.PurchaseService/RemoveFromCart"
	PurchaseService_GetMyCartItems_FullMethodName  = "/purchase.PurchaseService/GetMyCartItems"
	PurchaseService_Checkout_FullMethodName        = "/purchase.PurchaseService/Checkout"
	PurchaseService_HasPurchased_FullMethodName    = "/purchase.PurchaseService/HasPurchased"
	PurchaseService_GetMyPurchases_FullMethodName  = "/purchase.PurchaseService/GetMyPurchases"
	PurchaseService_GetAllPurchases_FullMethodName = "/purchase.PurchaseService/GetAllPurchases"
	PurchaseService_RefundPurchase_FullMethodName  = "/purchase.PurchaseService/RefundPurchase"
)

// PurchaseServiceClient is the client API for PurchaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- service ---
type PurchaseServiceClient interface {
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*CartResponse, error)
	RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...grpc.CallOption) (*CartResponse, error)
	GetMyCartItems(ctx context.Context, in *GetMyCartItemsRequest, opts ...grpc.CallOption) (*CartResponse, error)
	Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error)
	HasPurchased(ctx context.Context, in *HasPurchasedRequest, opts ...grpc.CallOption) (*HasPurchasedResponse, error)
	GetMyPurchases(ctx context.Context, in *GetMyPurchasesRequest, opts ...grpc.CallOption) (*GetMyPurchasesResponse, error)
	GetAllPurchases(ctx context.Context, in *GetAllPurchasesRequest, opts ...grpc.CallOption) (*GetAllPurchasesResponse, error)
	RefundPurchase(ctx context.Context, in *RefundPurchaseRequest, opts ...grpc.CallOption) (*RefundPurchaseResponse, error)
}

type purchaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchaseServiceClient(cc grpc.ClientConnInterface) PurchaseServiceClient {
	return &purchaseServiceClient{cc}
}

func (c *purchaseServiceClient) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, PurchaseService_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, PurchaseService_RemoveFromCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) GetMyCartItems(ctx context.Context, in *GetMyCartItemsRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, PurchaseService_GetMyCartItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, PurchaseService_Checkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) HasPurchased(ctx context.Context, in *HasPurchasedRequest, opts ...grpc.CallOption) (*HasPurchasedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasPurchasedResponse)
	err := c.cc.Invoke(ctx, PurchaseService_HasPurchased_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) GetMyPurchases(ctx context.Context, in *GetMyPurchasesRequest, opts ...grpc.CallOption) (*GetMyPurchasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyPurchasesResponse)
	err := c.cc.Invoke(ctx, PurchaseService_GetMyPurchases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) GetAllPurchases(ctx context.Context, in *GetAllPurchasesRequest, opts ...grpc.CallOption) (*GetAllPurchasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPurchasesResponse)
	err := c.cc.Invoke(ctx, PurchaseService_GetAllPurchases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) RefundPurchase(ctx context.Context, in *RefundPurchaseRequest, opts ...grpc.CallOption) (*RefundPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundPurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_RefundPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServiceServer is the server API for PurchaseService service.
// All implementations must embed UnimplementedPurchaseServiceServer
// for forward compatibility.
//
// --- service ---
type PurchaseServiceServer interface {
	AddToCart(context.Context, *AddToCartRequest) (*CartResponse, error)
	RemoveFromCart(context.Context, *RemoveFromCartRequest) (*CartResponse, error)
	GetMyCartItems(context.Context, *GetMyCartItemsRequest) (*CartResponse, error)
	Checkout(context.Context, *CheckoutRequest) (*CheckoutResponse, error)
	HasPurchased(context.Context, *HasPurchasedRequest) (*HasPurchasedResponse, error)
	GetMyPurchases(context.Context, *GetMyPurchasesRequest) (*GetMyPurchasesResponse, error)
	GetAllPurchases(context.Context, *GetAllPurchasesRequest) (*GetAllPurchasesResponse, error)
	RefundPurchase(context.Context, *RefundPurchaseRequest) (*RefundPurchaseResponse, error)
	mustEmbedUnimplementedPurchaseServiceServer()
}

// UnimplementedPurchaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPurchaseServiceServer struct{}

func (UnimplementedPurchaseServiceServer) AddToCart(context.Context, *AddToCartRequest) (*CartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedPurchaseServiceServer) RemoveFromCart(context.Context, *RemoveFromCartRequest) (*CartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromCart not implemented")
}
func (UnimplementedPurchaseServiceServer) GetMyCartItems(context.Context, *GetMyCartItemsRequest) (*CartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyCartItems not implemented")
}
func (UnimplementedPurchaseServiceServer) Checkout(context.Context, *CheckoutRequest) (*CheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkout not implemented")
}
func (UnimplementedPurchaseServiceServer) HasPurchased(context.Context, *HasPurchasedRequest) (*HasPurchasedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasPurchased not implemented")
}
func (UnimplementedPurchaseServiceServer) GetMyPurchases(context.Context, *GetMyPurchasesRequest) (*GetMyPurchasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyPurchases not implemented")
}
func (UnimplementedPurchaseServiceServer) GetAllPurchases(context.Context, *GetAllPurchasesRequest) (*GetAllPurchasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPurchases not implemented")
}
func (UnimplementedPurchaseServiceServer) RefundPurchase(context.Context, *RefundPurchaseRequest) (*RefundPurchaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundPurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) mustEmbedUnimplementedPurchaseServiceServer() {}
func (UnimplementedPurchaseServiceServer) testEmbeddedByValue()                         {}

// UnsafePurchaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PurchaseServiceServer will
// result in compilation errors.
type UnsafePurchaseServiceServer interface {
	mustEmbedUnimplementedPurchaseServiceServer()
}

func RegisterPurchaseServiceServer(s grpc.ServiceRegistrar, srv PurchaseServiceServer) {
	// If the following call panics, it indicates UnimplementedPurchaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PurchaseService_ServiceDesc, srv)
}

func _PurchaseService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).AddToCart(ctx, req.(*AddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_RemoveFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).RemoveFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_RemoveFromCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).RemoveFromCart(ctx, req.(*RemoveFromCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_GetMyCartItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCartItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).GetMyCartItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_GetMyCartItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).GetMyCartItems(ctx, req.(*GetMyCartItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_Checkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).Checkout(ctx, req.(*CheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_HasPurchased_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPurchasedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).HasPurchased(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_HasPurchased_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).HasPurchased(ctx, req.(*HasPurchasedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_GetMyPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).GetMyPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_GetMyPurchases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).GetMyPurchases(ctx, req.(*GetMyPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_GetAllPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).GetAllPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_GetAllPurchases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).GetAllPurchases(ctx, req.(*GetAllPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_RefundPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).RefundPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_RefundPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).RefundPurchase(ctx, req.(*RefundPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PurchaseService_ServiceDesc is the grpc.ServiceDesc for PurchaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PurchaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "purchase.PurchaseService",
	HandlerType: (*PurchaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToCart",
			Handler:    _PurchaseService_AddToCart_Handler,
		},
		{
			MethodName: "RemoveFromCart",
			Handler:    _PurchaseService_RemoveFromCart_Handler,
		},
		{
			MethodName: "GetMyCartItems",
			Handler:    _PurchaseService_GetMyCartItems_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _PurchaseService_Checkout_Handler,
		},
		{
			MethodName: "HasPurchased",
			Handler:    _PurchaseService_HasPurchased_Handler,
		},
		{
			MethodName: "GetMyPurchases",
			Handler:    _PurchaseService_GetMyPurchases_Handler,
		},
		{
			MethodName: "GetAllPurchases",
			Handler:    _PurchaseService_GetAllPurchases_Handler,
		},
		{
			MethodName: "RefundPurchase",
			Handler:    _PurchaseService_RefundPurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "purchase.proto",
}
