// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: purchase.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- order items ---
type OrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemRequest) Reset() {
	*x = OrderItemRequest{}
	mi := &file_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemRequest) ProtoMessage() {}

func (x *OrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemRequest.ProtoReflect.Descriptor instead.
func (*OrderItemRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItemRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *OrderItemRequest) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *OrderItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponse) Reset() {
	*x = OrderItemResponse{}
	mi := &file_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponse) ProtoMessage() {}

func (x *OrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponse.ProtoReflect.Descriptor instead.
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *OrderItemResponse) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *OrderItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// --- cart operations ---
type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *AddToCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *AddToCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFromCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Items         []*OrderItemResponse   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *CartResponse) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *CartResponse) GetItems() []*OrderItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type GetMyCartItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyCartItemsRequest) Reset() {
	*x = GetMyCartItemsRequest{}
	mi := &file_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyCartItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyCartItemsRequest) ProtoMessage() {}

func (x *GetMyCartItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyCartItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMyCartItemsRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{5}
}

// --- checkout / tokens ---
type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_purchase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *CheckoutRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,3,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	IssuedAt      string                 `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_purchase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{7}
}

func (x *TokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenResponse) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TokenResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TokenResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TokenResponse) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenResponse       `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_purchase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{8}
}

func (x *CheckoutResponse) GetTokens() []*TokenResponse {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// --- purchase checks ---
type HasPurchasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedRequest) Reset() {
	*x = HasPurchasedRequest{}
	mi := &file_purchase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedRequest) ProtoMessage() {}

func (x *HasPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedRequest.ProtoReflect.Descriptor instead.
func (*HasPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{9}
}

func (x *HasPurchasedRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *HasPurchasedRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type HasPurchasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchased     bool                   `protobuf:"varint,1,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedResponse) Reset() {
	*x = HasPurchasedResponse{}
	mi := &file_purchase_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedResponse) ProtoMessage() {}

func (x *HasPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedResponse.ProtoReflect.Descriptor instead.
func (*HasPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{10}
}

func (x *HasPurchasedResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

// --- listing / grouping purchases ---
type GetMyPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyPurchasesRequest) Reset() {
	*x = GetMyPurchasesRequest{}
	mi := &file_purchase_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPurchasesRequest) ProtoMessage() {}

func (x *GetMyPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPurchasesRequest.ProtoReflect.Descriptor instead.
func (*GetMyPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{11}
}

type GetMyPurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenResponse       `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyPurchasesResponse) Reset() {
	*x = GetMyPurchasesResponse{}
	mi := &file_purchase_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyPurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPurchasesResponse) ProtoMessage() {}

func (x *GetMyPurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPurchasesResponse.ProtoReflect.Descriptor instead.
func (*GetMyPurchasesResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyPurchasesResponse) GetTokens() []*TokenResponse {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type PurchasesByTourist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Tokens        []*TokenResponse       `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchasesByTourist) Reset() {
	*x = PurchasesByTourist{}
	mi := &file_purchase_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchasesByTourist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasesByTourist) ProtoMessage() {}

func (x *PurchasesByTourist) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasesByTourist.ProtoReflect.Descriptor instead.
func (*PurchasesByTourist) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{13}
}

func (x *PurchasesByTourist) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *PurchasesByTourist) GetTokens() []*TokenResponse {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetAllPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPurchasesRequest) Reset() {
	*x = GetAllPurchasesRequest{}
	mi := &file_purchase_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPurchasesRequest) ProtoMessage() {}

func (x *GetAllPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPurchasesRequest.ProtoReflect.Descriptor instead.
func (*GetAllPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{14}
}

type GetAllPurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*PurchasesByTourist  `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPurchasesResponse) Reset() {
	*x = GetAllPurchasesResponse{}
	mi := &file_purchase_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPurchasesResponse) ProtoMessage() {}

func (x *GetAllPurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPurchasesResponse.ProtoReflect.Descriptor instead.
func (*GetAllPurchasesResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllPurchasesResponse) GetPurchases() []*PurchasesByTourist {
	if x != nil {
		return x.Purchases
	}
	return nil
}

// --- refunds ---
type RefundPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPurchaseRequest) Reset() {
	*x = RefundPurchaseRequest{}
	mi := &file_purchase_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPurchaseRequest) ProtoMessage() {}

func (x *RefundPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPurchaseRequest.ProtoReflect.Descriptor instead.
func (*RefundPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{16}
}

func (x *RefundPurchaseRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RefundPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPurchaseResponse) Reset() {
	*x = RefundPurchaseResponse{}
	mi := &file_purchase_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPurchaseResponse) ProtoMessage() {}

func (x *RefundPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPurchaseResponse.ProtoReflect.Descriptor instead.
func (*RefundPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{17}
}

func (x *RefundPurchaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_purchase_proto protoreflect.FileDescriptor

const file_purchase_proto_rawDesc = "" +
	"\n" +
	"\x0epurchase.proto\x12\bpurchase\x1a\x1cgoogle/api/annotations.proto\"^\n" +
	"\x10OrderItemRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"_\n" +
	"\x11OrderItemResponse\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"J\n" +
	"\x10AddToCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"O\n" +
	"\x15RemoveFromCartRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"\x81\x01\n" +
	"\fCartResponse\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.purchase.OrderItemResponseR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\"\x17\n" +
	"\x15GetMyCartItemsRequest\"0\n" +
	"\x0fCheckoutRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\"\x8a\x01\n" +
	"\rTokenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x03 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\tissued_at\x18\x05 \x01(\tR\bissuedAt\"C\n" +
	"\x10CheckoutResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.purchase.TokenResponseR\x06tokens\"M\n" +
	"\x13HasPurchasedRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"4\n" +
	"\x14HasPurchasedResponse\x12\x1c\n" +
	"\tpurchased\x18\x01 \x01(\bR\tpurchased\"\x17\n" +
	"\x15GetMyPurchasesRequest\"I\n" +
	"\x16GetMyPurchasesResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.purchase.TokenResponseR\x06tokens\"d\n" +
	"\x12PurchasesByTourist\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12/\n" +
	"\x06tokens\x18\x02 \x03(\v2\x17.purchase.TokenResponseR\x06tokens\"\x18\n" +
	"\x16GetAllPurchasesRequest\"U\n" +
	"\x17GetAllPurchasesResponse\x12:\n" +
	"\tpurchases\x18\x01 \x03(\v2\x1c.purchase.PurchasesByTouristR\tpurchases\"2\n" +
	"\x15RefundPurchaseRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"2\n" +
	"\x16RefundPurchaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc7\x06\n" +
	"\x0fPurchaseService\x12Q\n" +
	"\tAddToCart\x12\x1a.purchase.AddToCartRequest\x1a\x16.purchase.CartResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/cart\x12b\n" +
	"\x0eRemoveFromCart\x12\x1f.purchase.RemoveFromCartRequest\x1a\x16.purchase.CartResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/cart/{tour_id}\x12X\n" +
	"\x0eGetMyCartItems\x12\x1f.purchase.GetMyCartItemsRequest\x1a\x16.purchase.CartResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/cart\x12W\n" +
	"\bCheckout\x12\x19.purchase.CheckoutRequest\x1a\x1a.purchase.CheckoutResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/checkout\x12~\n" +
	"\fHasPurchased\x12\x1d.purchase.HasPurchasedRequest\x1a\x1e.purchase.HasPurchasedResponse\"/\x82\xd3\xe4\x93\x02)\x12'/purchases/{tourist_id}/tours/{tour_id}\x12j\n" +
	"\x0eGetMyPurchases\x12\x1f.purchase.GetMyPurchasesRequest\x1a .purchase.GetMyPurchasesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/purchases/my\x12j\n" +
	"\x0fGetAllPurchases\x12 .purchase.GetAllPurchasesRequest\x1a!.purchase.GetAllPurchasesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/purchases\x12r\n" +
	"\x0eRefundPurchase\x12\x1f.purchase.RefundPurchaseRequest\x1a .purchase.RefundPurchaseResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/purchases/{token_id}B\x03Z\x01.b\x06proto3"

var (
	file_purchase_proto_rawDescOnce sync.Once
	file_purchase_proto_rawDescData []byte
)

func file_purchase_proto_rawDescGZIP() []byte {
	file_purchase_proto_rawDescOnce.Do(func() {
		file_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)))
	})
	return file_purchase_proto_rawDescData
}

var file_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_purchase_proto_goTypes = []any{
	(*OrderItemRequest)(nil),        // 0: purchase.OrderItemRequest
	(*OrderItemResponse)(nil),       // 1: purchase.OrderItemResponse
	(*AddToCartRequest)(nil),        // 2: purchase.AddToCartRequest
	(*RemoveFromCartRequest)(nil),   // 3: purchase.RemoveFromCartRequest
	(*CartResponse)(nil),            // 4: purchase.CartResponse
	(*GetMyCartItemsRequest)(nil),   // 5: purchase.GetMyCartItemsRequest
	(*CheckoutRequest)(nil),         // 6: purchase.CheckoutRequest
	(*TokenResponse)(nil),           // 7: purchase.TokenResponse
	(*CheckoutResponse)(nil),        // 8: purchase.CheckoutResponse
	(*HasPurchasedRequest)(nil),     // 9: purchase.HasPurchasedRequest
	(*HasPurchasedResponse)(nil),    // 10: purchase.HasPurchasedResponse
	(*GetMyPurchasesRequest)(nil),   // 11: purchase.GetMyPurchasesRequest
	(*GetMyPurchasesResponse)(nil),  // 12: purchase.GetMyPurchasesResponse
	(*PurchasesByTourist)(nil),      // 13: purchase.PurchasesByTourist
	(*GetAllPurchasesRequest)(nil),  // 14: purchase.GetAllPurchasesRequest
	(*GetAllPurchasesResponse)(nil), // 15: purchase.GetAllPurchasesResponse
	(*RefundPurchaseRequest)(nil),   // 16: purchase.RefundPurchaseRequest
	(*RefundPurchaseResponse)(nil),  // 17: purchase.RefundPurchaseResponse
}
var file_purchase_proto_depIdxs = []int32{
	1,  // 0: purchase.CartResponse.items:type_name -> purchase.OrderItemResponse
	7,  // 1: purchase.CheckoutResponse.tokens:type_name -> purchase.TokenResponse
	7,  // 2: purchase.GetMyPurchasesResponse.tokens:type_name -> purchase.TokenResponse
	7,  // 3: purchase.PurchasesByTourist.tokens:type_name -> purchase.TokenResponse
	13, // 4: purchase.GetAllPurchasesResponse.purchases:type_name -> purchase.PurchasesByTourist
	2,  // 5: purchase.PurchaseService.AddToCart:input_type -> purchase.AddToCartRequest
	3,  // 6: purchase.PurchaseService.RemoveFromCart:input_type -> purchase.RemoveFromCartRequest
	5,  // 7: purchase.PurchaseService.GetMyCartItems:input_type -> purchase.GetMyCartItemsRequest
	6,  // 8: purchase.PurchaseService.Checkout:input_type -> purchase.CheckoutRequest
	9,  // 9: purchase.PurchaseService.HasPurchased:input_type -> purchase.HasPurchasedRequest
	11, // 10: purchase.PurchaseService.GetMyPurchases:input_type -> purchase.GetMyPurchasesRequest
	14, // 11: purchase.PurchaseService.GetAllPurchases:input_type -> purchase.GetAllPurchasesRequest
	16, // 12: purchase.PurchaseService.RefundPurchase:input_type -> purchase.RefundPurchaseRequest
	4,  // 13: purchase.PurchaseService.AddToCart:output_type -> purchase.CartResponse
	4,  // 14: purchase.PurchaseService.RemoveFromCart:output_type -> purchase.CartResponse
	4,  // 15: purchase.PurchaseService.GetMyCartItems:output_type -> purchase.CartResponse
	8,  // 16: purchase.PurchaseService.Checkout:output_type -> purchase.CheckoutResponse
	10, // 17: purchase.PurchaseService.HasPurchased:output_type -> purchase.HasPurchasedResponse
	12, // 18: purchase.PurchaseService.GetMyPurchases:output_type -> purchase.GetMyPurchasesResponse
	15, // 19: purchase.PurchaseService.GetAllPurchases:output_type -> purchase.GetAllPurchasesResponse
	17, // 20: purchase.PurchaseService.RefundPurchase:output_type -> purchase.RefundPurchaseResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_purchase_proto_init() }
func file_purchase_proto_init() {
	if File_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchase_proto_goTypes,
		DependencyIndexes: file_purchase_proto_depIdxs,
		MessageInfos:      file_purchase_proto_msgTypes,
	}.Build()
	File_purchase_proto = out.File
	file_purchase_proto_goTypes = nil
	file_purchase_proto_depIdxs = nil
}
