spring:
  application:
    name: follower-microservice
  
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  
  data:
    neo4j:
      auto-index: validate
      repositories:
        enabled: true

services:
  stakeholders-url: http://localhost:8000
  blog-url: http://localhost:8080

server:
  port: 8082
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.follower: DEBUG
    org.springframework.data.neo4j: DEBUG

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
