# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x0cstakeholders\"$\n\x11GetProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x82\x01\n\x0fProfileResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\x10\n\x08imageUrl\x18\x04 \x01(\t\x12\x11\n\tbiography\x18\x05 \x01(\t\x12\r\n\x05quote\x18\x06 \x01(\t\x12\x0f\n\x07user_id\x18\x07 \x01(\x05\"\xba\x01\n\rProfileCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x08lastname\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08imageUrl\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tbiography\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05quote\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x0f\n\x07user_id\x18\x06 \x01(\x05\x42\x0b\n\t_lastnameB\x0b\n\t_imageUrlB\x0c\n\n_biographyB\x08\n\x06_quote\"\xc8\x01\n\rProfileUpdate\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08lastname\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08imageUrl\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tbiography\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05quote\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x0f\n\x07user_id\x18\x06 \x01(\x05\x42\x07\n\x05_nameB\x0b\n\t_lastnameB\x0b\n\t_imageUrlB\x0c\n\n_biographyB\x08\n\x06_quote2\xf8\x01\n\x0eProfileService\x12K\n\rCreateProfile\x12\x1b.stakeholders.ProfileCreate\x1a\x1d.stakeholders.ProfileResponse\x12L\n\nGetProfile\x12\x1f.stakeholders.GetProfileRequest\x1a\x1d.stakeholders.ProfileResponse\x12K\n\rUpdateProfile\x12\x1b.stakeholders.ProfileUpdate\x1a\x1d.stakeholders.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROFILEREQUEST']._serialized_start=31
  _globals['_GETPROFILEREQUEST']._serialized_end=67
  _globals['_PROFILERESPONSE']._serialized_start=70
  _globals['_PROFILERESPONSE']._serialized_end=200
  _globals['_PROFILECREATE']._serialized_start=203
  _globals['_PROFILECREATE']._serialized_end=389
  _globals['_PROFILEUPDATE']._serialized_start=392
  _globals['_PROFILEUPDATE']._serialized_end=592
  _globals['_PROFILESERVICE']._serialized_start=595
  _globals['_PROFILESERVICE']._serialized_end=843
# @@protoc_insertion_point(module_scope)
