// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: profile.proto

package stakeholders

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_TOURIST Role = 0
	Role_AUTHOR  Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "TOURIST",
		1: "AUTHOR",
	}
	Role_value = map[string]int32{
		"TOURIST": 0,
		"AUTHOR":  1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Biography     string                 `protobuf:"bytes,5,opt,name=biography,proto3" json:"biography,omitempty"`
	Quote         string                 `protobuf:"bytes,6,opt,name=quote,proto3" json:"quote,omitempty"`
	UserId        int32                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,8,opt,name=role,proto3,enum=stakeholders.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *ProfileResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProfileResponse) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *ProfileResponse) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *ProfileResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProfileResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_TOURIST
}

type ProfileCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lastname      *string                `protobuf:"bytes,2,opt,name=lastname,proto3,oneof" json:"lastname,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,3,opt,name=imageUrl,proto3,oneof" json:"imageUrl,omitempty"`
	Biography     *string                `protobuf:"bytes,4,opt,name=biography,proto3,oneof" json:"biography,omitempty"`
	Quote         *string                `protobuf:"bytes,5,opt,name=quote,proto3,oneof" json:"quote,omitempty"`
	UserId        int32                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,7,opt,name=role,proto3,enum=stakeholders.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileCreate) Reset() {
	*x = ProfileCreate{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCreate) ProtoMessage() {}

func (x *ProfileCreate) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCreate.ProtoReflect.Descriptor instead.
func (*ProfileCreate) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileCreate) GetLastname() string {
	if x != nil && x.Lastname != nil {
		return *x.Lastname
	}
	return ""
}

func (x *ProfileCreate) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *ProfileCreate) GetBiography() string {
	if x != nil && x.Biography != nil {
		return *x.Biography
	}
	return ""
}

func (x *ProfileCreate) GetQuote() string {
	if x != nil && x.Quote != nil {
		return *x.Quote
	}
	return ""
}

func (x *ProfileCreate) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProfileCreate) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_TOURIST
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\fstakeholders\x1a\x1cgoogle/api/annotations.proto\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"\xe2\x01\n" +
	"\x0fProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x1a\n" +
	"\bimageUrl\x18\x04 \x01(\tR\bimageUrl\x12\x1c\n" +
	"\tbiography\x18\x05 \x01(\tR\tbiography\x12\x14\n" +
	"\x05quote\x18\x06 \x01(\tR\x05quote\x12\x17\n" +
	"\auser_id\x18\a \x01(\x05R\x06userId\x12&\n" +
	"\x04role\x18\b \x01(\x0e2\x12.stakeholders.RoleR\x04role\"\x96\x02\n" +
	"\rProfileCreate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\blastname\x18\x02 \x01(\tH\x00R\blastname\x88\x01\x01\x12\x1f\n" +
	"\bimageUrl\x18\x03 \x01(\tH\x01R\bimageUrl\x88\x01\x01\x12!\n" +
	"\tbiography\x18\x04 \x01(\tH\x02R\tbiography\x88\x01\x01\x12\x19\n" +
	"\x05quote\x18\x05 \x01(\tH\x03R\x05quote\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x05R\x06userId\x12&\n" +
	"\x04role\x18\a \x01(\x0e2\x12.stakeholders.RoleR\x04roleB\v\n" +
	"\t_lastnameB\v\n" +
	"\t_imageUrlB\f\n" +
	"\n" +
	"_biographyB\b\n" +
	"\x06_quote*\x1f\n" +
	"\x04Role\x12\v\n" +
	"\aTOURIST\x10\x00\x12\n" +
	"\n" +
	"\x06AUTHOR\x10\x012\xe5\x01\n" +
	"\x0eProfileService\x12h\n" +
	"\rCreateProfile\x12\x1b.stakeholders.ProfileCreate\x1a\x1d.stakeholders.ProfileResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/profiles/create\x12i\n" +
	"\n" +
	"GetProfile\x12\x1f.stakeholders.GetProfileRequest\x1a\x1d.stakeholders.ProfileResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/profiles/{user_id}BZZXhttps://github.com/K-atarinaVujovic/Tourism-App-Microservices/Gateway/proto/stakeholdersb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_profile_proto_goTypes = []any{
	(Role)(0),                 // 0: stakeholders.Role
	(*GetProfileRequest)(nil), // 1: stakeholders.GetProfileRequest
	(*ProfileResponse)(nil),   // 2: stakeholders.ProfileResponse
	(*ProfileCreate)(nil),     // 3: stakeholders.ProfileCreate
}
var file_profile_proto_depIdxs = []int32{
	0, // 0: stakeholders.ProfileResponse.role:type_name -> stakeholders.Role
	0, // 1: stakeholders.ProfileCreate.role:type_name -> stakeholders.Role
	3, // 2: stakeholders.ProfileService.CreateProfile:input_type -> stakeholders.ProfileCreate
	1, // 3: stakeholders.ProfileService.GetProfile:input_type -> stakeholders.GetProfileRequest
	2, // 4: stakeholders.ProfileService.CreateProfile:output_type -> stakeholders.ProfileResponse
	2, // 5: stakeholders.ProfileService.GetProfile:output_type -> stakeholders.ProfileResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	file_profile_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		EnumInfos:         file_profile_proto_enumTypes,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
