syntax = "proto3";
package stakeholders;

option go_package = "https://github.com/K-atarinaVujovic/Tourism-App-Microservices/Gateway/proto/stakeholders";

import "google/api/annotations.proto";

enum Role {
  TOURIST = 0;
  AUTHOR = 1;
}

service ProfileService {
  rpc CreateProfile(ProfileCreate) returns (ProfileResponse) {
    option (google.api.http) = {
      post: "/profiles/create"
      body: "*"
    };
  }
  rpc GetProfile(GetProfileRequest) returns (ProfileResponse) {
    option (google.api.http) = {
      get: "/profiles/{user_id}"
    };
  }
}

message GetProfileRequest {
  int32 user_id = 1;
}

message ProfileResponse {
  string id = 1;
  string name = 2;
  string lastname = 3;
  string imageUrl = 4;
  string biography = 5;
  string quote = 6;
  int32 user_id = 7;
  Role role = 8;
}

message ProfileCreate {
  string name = 1;
  optional string lastname = 2;
  optional string imageUrl = 3;
  optional string biography = 4;
  optional string quote = 5;
  int32 user_id = 6;
  Role role = 7;
}